---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.vrungel.maxvk.com
  resources:
  - setups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.vrungel.maxvk.com
  resources:
  - setups/finalizers
  verbs:
  - update
- apiGroups:
  - crd.vrungel.maxvk.com
  resources:
  - setups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.vrungel.maxvk.com
  resources:
  - rolebindwatchers
  - rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.vrungel.maxvk.com
  resources:
  - rolebindwatchers/finalizers
  - rules/finalizers
  verbs:
  - update
- apiGroups:
  - security.vrungel.maxvk.com
  resources:
  - rolebindwatchers/status
  - rules/status
  verbs:
  - get
  - patch
  - update
